// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/outside/data/ent/article"
	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/outside/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescLang is the schema descriptor for lang field.
	articleDescLang := articleFields[7].Descriptor()
	// article.LangValidator is a validator for the "lang" field. It is called by the builders before save.
	article.LangValidator = articleDescLang.Validators[0].(func(string) error)
	// articleDescIsPublished is the schema descriptor for is_published field.
	articleDescIsPublished := articleFields[11].Descriptor()
	// article.DefaultIsPublished holds the default value on creation for the is_published field.
	article.DefaultIsPublished = articleDescIsPublished.Default.(bool)
	// articleDescCdate is the schema descriptor for cdate field.
	articleDescCdate := articleFields[12].Descriptor()
	// article.DefaultCdate holds the default value on creation for the cdate field.
	article.DefaultCdate = articleDescCdate.Default.(func() time.Time)
	// articleDescIsProcessed is the schema descriptor for is_processed field.
	articleDescIsProcessed := articleFields[15].Descriptor()
	// article.DefaultIsProcessed holds the default value on creation for the is_processed field.
	article.DefaultIsProcessed = articleDescIsProcessed.Default.(bool)
}
