// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/biz"
	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/conf"
	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/outside/data"
	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/server"
	"gitlab.com/mcsolutions/find-psy/back/article-v1/internal/service"
	"gitlab.com/mcsolutions/find-psy/proto/gen/go/common"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(commonServer *common.Server, jwks *common.Jwks, business *conf.Business, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	iCache := data.NewCache(dataData, logger)
	articleUsecase, err := biz.NewArticleUsecase(business, articleRepo, iCache, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	articleService := service.NewArticleService(articleUsecase, logger)
	grpcServer, err := server.NewGRPCServer(commonServer, jwks, articleService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer, err := server.NewHTTPServer(commonServer, articleService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
