// Code generated by entc, DO NOT EDIT.

package article

import (
	"time"
)

const (
	// Label holds the string label denoting the article type in the database.
	Label = "article"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldLatinized holds the string denoting the latinized field in the database.
	FieldLatinized = "latinized"
	// FieldHTML holds the string denoting the html field in the database.
	FieldHTML = "html"
	// FieldShortText holds the string denoting the short_text field in the database.
	FieldShortText = "short_text"
	// FieldLang holds the string denoting the lang field in the database.
	FieldLang = "lang"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldB17Account holds the string denoting the b17_account field in the database.
	FieldB17Account = "b17_account"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldIsPublished holds the string denoting the is_published field in the database.
	FieldIsPublished = "is_published"
	// FieldCdate holds the string denoting the cdate field in the database.
	FieldCdate = "cdate"
	// FieldUdate holds the string denoting the udate field in the database.
	FieldUdate = "udate"
	// FieldPubDate holds the string denoting the pub_date field in the database.
	FieldPubDate = "pub_date"
	// FieldIsProcessed holds the string denoting the is_processed field in the database.
	FieldIsProcessed = "is_processed"
	// Table holds the table name of the article in the database.
	Table = "article"
)

// Columns holds all SQL columns for article fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldUserName,
	FieldTitle,
	FieldLatinized,
	FieldHTML,
	FieldShortText,
	FieldLang,
	FieldTags,
	FieldB17Account,
	FieldSource,
	FieldIsPublished,
	FieldCdate,
	FieldUdate,
	FieldPubDate,
	FieldIsProcessed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LangValidator is a validator for the "lang" field. It is called by the builders before save.
	LangValidator func(string) error
	// DefaultIsPublished holds the default value on creation for the "is_published" field.
	DefaultIsPublished bool
	// DefaultCdate holds the default value on creation for the "cdate" field.
	DefaultCdate func() time.Time
	// DefaultIsProcessed holds the default value on creation for the "is_processed" field.
	DefaultIsProcessed bool
)
